apiVersion: v1
kind: Service
metadata:
  name: mysql-db-svc
spec:
  selector:
    app: mysql-db
    tier: backend
  ports:
    - port: 3306
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
  labels:
    app: mysql-db
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
      tier: backend
  template:
    metadata:
      labels:
        app: mysql-db
        tier: backend
    spec:
      tolerations:
        - key: "tier"
          operator: "Equal"
          value: "backend"
          effect: "NoSchedule"
      volumes:
        - name: pv-storage
          persistentVolumeClaim: 
            claimName: pv-claim
      containers:
        - name: mysql-db
          image: hshar/mysql:5.5
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              name: pv-storage
